name: Reusable build all workflow

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      toolchain:
        required: true
        type: string      

jobs:
  build-in-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:${{ inputs.toolchain}}
    defaults:
      run:
        shell: bash

    steps:
      - name: disk space
        run: |
          sudo dh -h
          sudo rm -rf /usr/lib/jvm /usr/share/dotnet /usr/share/swift
          sudo rm -rf /usr/local/.ghcup /usr/local/julia* /usr/local/lib/android
          sudo rm -rf /usr/local/share/chromium /opt/microsoft /opt/google
          sudo rm -rf /opt/az /usr/local/share/powershell /opt/hostedtoolcache
          sudo df -h

