name: Reusable build all workflow

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      toolchain:
        required: true
        type: string      

jobs:
  build-in-docker:
    runs-on: ubuntu-latest

    steps:
      - name: disk space
        run: |
          df -h
          rm -rf /usr/lib/jvm /usr/share/dotnet /usr/share/swift
          rm -rf /usr/local/.ghcup /usr/local/julia* /usr/local/lib/android
          rm -rf /usr/local/share/chromium /opt/microsoft /opt/google
          rm -rf /opt/az /usr/local/share/powershell /opt/hostedtoolcache
          df -h

